import type { TutorialStep } from './types';

/**
 * Declarative guided tour. Reorder / extend by editing this list only.
 */
export const TUTORIAL_STEPS: TutorialStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to QuickCal',
    body: 'A short tour of the fastest way to log calories. Skip anytime — your data stays yours.',
    advanceOn: 'next',
    primaryLabel: 'Start',
  },
  {
    id: 'library-add',
    title: 'Add to your library',
    body: 'Tap Add to create foods and meals you reuse. Your personal library — no giant database.',
    tab: 'Library',
    targetId: 'library.add',
    advanceOn: 'action',
    action: 'opened-add-item',
    primaryLabel: 'Next',
  },
  {
    id: 'quick-vs-portion',
    title: 'Quick Log vs Portion',
    body: 'Quick Log = one tap. Portion = choose 1 / 1.5 / 2 / Custom first. Pick what matches how you eat.',
    tab: 'Library',
    targetId: 'library.mode',
    advanceOn: 'action',
    action: 'selected-logging-mode',
    primaryLabel: 'Next',
  },
  {
    id: 'pinning',
    title: 'Pin for speed',
    body: 'Pin up to 21 items so they appear on Home for one-tap logging.',
    tab: 'Library',
    targetId: 'library.pin',
    advanceOn: 'next',
    primaryLabel: 'Next',
  },
  {
    id: 'home-pins',
    title: 'Pinned on Home',
    body: 'Your pins live here for the fastest log path.',
    tab: 'Home',
    targetId: 'home.pins',
    advanceOn: 'next',
    primaryLabel: 'Next',
  },
  {
    id: 'logging',
    title: 'Log and watch remaining',
    body: 'Tap a pin (or Quick Log item). The calorie card above updates immediately — no OK dialogs.',
    tab: 'Home',
    targetId: 'home.pins',
    advanceOn: 'action',
    action: 'logged-library-item',
    primaryLabel: 'Next',
  },
  {
    id: 'history',
    title: 'History',
    body: 'Browse past days, edit or delete entries, and check daily totals.',
    tab: 'History',
    targetId: 'history.day',
    advanceOn: 'next',
    primaryLabel: 'Next',
  },
  {
    id: 'settings-theme',
    title: 'Settings & themes',
    body: 'Goals, retention, profile, and more. Themes can be changed here anytime.',
    tab: 'Settings',
    targetId: 'settings.theme',
    advanceOn: 'next',
    primaryLabel: 'Next',
  },
  {
    id: 'finish',
    title: 'You’re ready',
    body: 'Build your library, pin favorites, and log in seconds. Replay this tour from Settings whenever you want.',
    advanceOn: 'next',
    primaryLabel: 'Done',
  },
];
