export const colors = {
  background: '#F6F7F6',
  surface: '#FFFFFF',
  surfaceMuted: '#EEF1EF',
  card: '#FFFFFF',
  text: '#141816',
  textSecondary: '#6B736E',
  textTertiary: '#9AA39C',
  textOnAccent: '#FFFFFF',
  border: '#E4E8E5',
  borderSubtle: '#EEF1EF',
  inputBackground: '#FFFFFF',
  inputBorder: '#E4E8E5',
  tabActive: '#0F9F6E',
  tabInactive: '#9AA39C',
  charcoal: '#141816',
  emerald: '#0F9F6E',
  emeraldDeep: '#047857',
  lime: '#A3E635',
  goalUnderStart: '#059669',
  goalUnderEnd: '#84CC16',
  goalOverStart: '#E11D48',
  goalOverEnd: '#FB7185',
  progressTrack: '#E8EDE9',
  pin: '#0F9F6E',
  placeholder: '#A3ABA6',
  thumbnail: '#E8EDE9',
  overlay: 'rgba(20, 24, 22, 0.04)',
} as const;

export const gradients = {
  emerald: [colors.goalUnderStart, colors.goalUnderEnd] as const,
  over: [colors.goalOverStart, colors.goalOverEnd] as const,
  button: [colors.charcoal, '#1F2933'] as const,
  buttonAccent: [colors.emeraldDeep, colors.emerald] as const,
} as const;
